### ISSUE TITLE
Game Time of a fresh new save shows up as 12 hours 30 seconds played

### ISSUE THREAD

**Issue by Psojed** [denbkh/stoneshard-save-editor#3]
![2022-08-17_124404](https://user-images.githubusercontent.com/12875358/185100272-e9628ff1-a365-47a7-9aa4-725f7c746a99.png)

Perhaps related to 12/24hr time format usage?
I use 24hr time format as you can see.

**Comment by denbkh** [comment]
This time is actually stored in a save file. The program just displays it without any modification. I have no idea why the game devs store 12h 30seconds. 
Works as expected.
